### ISSUE TITLE
Migrator looks for work too frequently

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#106]
Based on access logs and REST find requests seen in graphite it looks like migrator looks for work every 1 or 2 seconds.  Frequent is OK, but it shouldn't be this frequent.

**Comment by jewzaam** [comment]
Guess I was tired last night or just missed it.  The migrator is not able to parse the response for getting the next available job.  Not sure why yet.  The response looks good at a glance, it's valid JSON.  

```
Exception in thread "ConsistencyCheckerRunner" com.netflix.hystrix.exception.HystrixRuntimeException: migrator:primaryClient failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:760)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:747)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1388)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1278)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:921)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1347)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1247)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:386)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:366)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1019)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1015)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7556)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:379)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:335)
	at com.redhat.lightblue.client.hystrix.LightblueHystrixClient.data(LightblueHystrixClient.java:95)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getNextAvailableJob(ConsistencyChecker.java:225)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:161)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.redhat.lightblue.client.http.LightblueHttpClientException: Error sending lightblue request: {"query":{"field":"whenAvailableDate","op":">=","rvalue":"20150318T14:08:36.951+0000"},"projection":[{"field":"*","include":true,"recursive":true}],"sort":[{"whenAvailableDate":"$asc"}], "range": [0,1]}
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:136)
	at com.redhat.lightblue.client.hystrix.LightblueHystrixClient$DataTypeHystrixCommand.run(LightblueHystrixClient.java:69)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	... 48 more
Caused by: com.redhat.lightblue.client.response.LightblueResponseParseException: Error parsing lightblue response: {"status":"COMPLETE","modifiedCount":0,"matchCount":6927,"processed":[{"startDate":"20150318T14:00:00.000+0000","jobExecutions":[{"actualEndDate":"20150317T22:20:14.988+0000","ownerName":"migrator","consistentDocumentCount":0,"completedFlag":true,"hostName":"hostname","actualStartDate":"20150317T22:20:11.653+0000","overwrittenDocumentCount":0,"pid":"2484@hostname","inconsistentDocumentCount":0,"processedDocumentCount":0}],"endDate":"20150318T15:00:00.000+0000","whenAvailableDate":"20150318T15:00:00.000+0000","configurationName":"entityName","lastUpdateDate":"20150317T13:51:23.000+0000","creationDate":"20150317T13:51:23.000+0000","expectedExecutionMilliseconds":30000,"jobExecutions#":1,"createdBy":"nmalik","_id":"entityNameJob_203848","lastUpdatedBy":"nmalik","objectType":"migrationJob"},{"startDate":"20150318T15:00:00.000+0000","jobExecutions":[{"actualEndDate":"20150317T22:20:15.250+0000","ownerName":"migrator","consistentDocumentCount":0,"completedFlag":true,"hostName":"hostname","actualStartDate":"20150317T22:20:11.935+0000","overwrittenDocumentCount":0,"pid":"2484@hostname","inconsistentDocumentCount":0,"processedDocumentCount":0}],"endDate":"20150318T16:00:00.000+0000","whenAvailableDate":"20150318T16:00:00.000+0000","configurationName":"entityName","lastUpdateDate":"20150317T13:51:23.000+0000","creationDate":"20150317T13:51:23.000+0000","expectedExecutionMilliseconds":30000,"jobExecutions#":1,"createdBy":"nmalik","_id":"entityNameJob_203849","lastUpdatedBy":"nmalik","objectType":"migrationJob"}]}

	at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:119)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:134)
	... 50 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.redhat.lightblue.migrator.consistency.MigrationJob out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:569)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1121)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:123)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:117)
	... 51 more
```

**Comment by jewzaam** [comment]
Ah, it's fetching range(0, 1).
Range is inclusive.  Also it's expecting a single instance of MigrationJob to be returned.  Not sure that's valid.  Will update to account for that if necessary after testing.

**Comment by luan-cestari** [comment]
It seems to me that this is related to the ligthblue clietn issue that I'm working on https://github.com/lightblue-platform/lightblue-client/issues/28 . The problem is that the Class informed by the parameter is expecting just one object and in the response it found an array and it throws this exception

**Comment by jewzaam** [comment]
I'm pretty sure we always return an array now but I don't know how the client handles that case.

**Comment by luan-cestari** [comment]
@jewzaam Sorry, I thought it was some how related as I saw the root of the exception  on that issue on client project but after I dig inside migrator I found it is a misuse of LightblueClient as it asking for the range 0 to 1 (so two items at most) but the type informed is a single instance. May I pick this issue and create a PR to solve this? 
https://github.com/luan-cestari/lightblue-migrator/blob/master/consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java#L208-L210
it should be
job = client.data(findRequest, MigrationJob[].class);

**Comment by jewzaam** [comment]
Fix is in PR https://github.com/lightblue-platform/lightblue-migrator/pull/110
