### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#125]
Saw this last night running migrations in dev:

```
com.redhat.lightblue.client.LightblueClientConfigurationException: Could not read properties file from path, /etc/migrator/primary-lightblue-client.properties
        at com.redhat.lightblue.client.PropertiesLightblueClientConfiguration.fromPath(PropertiesLightblueClientConfiguration.java:113)
        at com.redhat.lightblue.client.http.LightblueHttpClient.<init>(LightblueHttpClient.java:51)
        at com.redhat.lightblue.migrator.consistency.MigrationJob.configureClients(MigrationJob.java:388)
        at com.redhat.lightblue.migrator.consistency.MigrationJob.run(MigrationJob.java:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: /etc/migrator/primary-lightblue-client.properties: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
        at java.nio.file.Files.newInputStream(Files.java:108)
        at com.redhat.lightblue.client.PropertiesLightblueClientConfiguration.fromPath(PropertiesLightblueClientConfiguration.java:109)

```

**Comment by luan-cestari** [comment]
This should be a puppet issue IMHO as it will have to deal with some OS properties.

**Comment by luan-cestari** [comment]
Only if we are leaking the file descriptors, which I would assume that we closed them properly

**Comment by jewzaam** [comment]
I assume that too, but haven't checked.  I would say that's the likely issue, not cleaning up resources.  We have jvm stats for this pushed to graphite.  It includes open file descriptors from the jvm observer.  Could take a look there to see what the JVM things is going on as a start.

----- Original Message -----

**Comment by jewzaam** [comment]
This turned out to be caused by a fork of this project that has some internal logic for fetching records from a relational database directly.  Marking this as won't fix.  For anybody interested, the issue was no connection pooling and poor management of connections.  Updated to use c3p0 and try-with-resource for Connection, PreparedStatement, and ResultSet objects.
