### ISSUE TITLE
Add integration test capability to migrator

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#142]
Getting this in dev right now, over and over:

```
2015-03-27 15:42:00,037 [WorkerMonitor] com.redhat.lightblue.migrator.consistency.ConsistencyCheckerDaemon INFO - Starting ConsistencyCheckerDaemon
2015-03-27 15:42:00,038 [ConsistencyCheckerRunner] com.redhat.lightblue.migrator.consistency.ConsistencyChecker INFO - From CLI - consistencyCheckerName: hystrix hostName: lightbluehystrix1.dev.a1.vary.redhat.com
2015-03-27 15:42:01,620 [ConsistencyCheckerRunner] com.redhat.lightblue.migrator.consistency.ConsistencyChecker INFO - Loading jobs for terms
Exception in thread "ConsistencyCheckerRunner" java.lang.IllegalArgumentException: $in operator is not allowed. Allowed options are: [$gte, $eq, $neq, $lt, <=, !=, $lte, >=, >, =, <]
        at com.redhat.lightblue.client.expression.query.ValueQuery.<init>(ValueQuery.java:37)
        at com.redhat.lightblue.client.expression.query.ValueQuery.withValue(ValueQuery.java:75)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getMigrationJobs(ConsistencyChecker.java:219)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:145)
        at java.lang.Thread.run(Thread.java:745)
2015-03-27 15:42:04,974 [WorkerMonitor] com.redhat.lightblue.migrator.consistency.ConsistencyCheckerDaemon WARN - ConsistencyChecker has stopped running, attempting restart.

```

**Comment by dcrissman** [comment]
The issue is actually coming from the lightblue-client. It seem that the ValueQuery (or any Query implementation for that matter) does not support $in or $nin operations.

**Comment by dcrissman** [comment]
Creating https://github.com/lightblue-platform/lightblue-client/issues/78 to add support for NaryExpressionOperation operations.

**Comment by jewzaam** [comment]
@dcrissman that's one path forward, but what about for migrator for now just making this a set of and/or conditions as appropriate?

**Comment by dcrissman** [comment]
A verbose solution, but I see no reason that wouldn't suffice as a work around.

Regarding the stated intention of this issue "Add unit test of ConsistencyChecker", that is really going to need to be an integration test, that thankfully with the work we have recently done should be easily doable. That said, some of the PRs I have out there would make this easier.

**Comment by jewzaam** [comment]
List them and we can focus on getting them merged.

**Comment by dcrissman** [comment]
* https://github.com/lightblue-platform/lightblue-rest/issues/123
* https://github.com/lightblue-platform/lightblue-core/pull/356
* https://github.com/lightblue-platform/lightblue-mongo/pull/92
* https://github.com/lightblue-platform/lightblue-test-utils/pull/8

**Comment by dcrissman** [comment]
Thinking more about integration testing the migrator, it uses multiple lb clients which would not be supported with the current implementation of AbstractCRUDControllerWithRest. I created an issue to investigate the possibility.
https://github.com/lightblue-platform/lightblue-test-utils/issues/10

**Comment by dcrissman** [comment]
I sort of take my last comment back. The migrator could run it's tests with a single lightblue instance and just use that as the source, destination, and primary.

**Comment by dcrissman** [comment]
Run into https://github.com/lightblue-platform/lightblue-test-utils/issues/13 while testing. Essentially, the metadata requires a certain permission, but at this time I am uncertain if there is a way to test with that permission.
