### ISSUE TITLE
IllegalArgumentException: + operator is not allowed

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#145]
```
IllegalArgumentException: + operator is not allowed. Allowed options are: [$eq, $gte, $neq, $nin, $lt, >=, $in, $not_in, $gt, <=, !=, $lte, >, =, <]
        at com.redhat.lightblue.client.expression.query.ValueQuery.<init>(ValueQuery.java:45)
        at com.redhat.lightblue.client.expression.query.ValueQuery.withValue(ValueQuery.java:99)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getMigrationJobs(ConsistencyChecker.java:219)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dcrissman** [comment]
The problematic line of code is:
```java
withValue("whenAvailableDate + expectedExecutionMilliseconds < " + ClientConstants.getDateFormat().format(new Date()))
```

Is this even a valid expression?

**Comment by jewzaam** [comment]
The client supports a single operation in a value query.  And I don't think we can do addition within the query language directly.  To do this we'd have to fetch the record first then do the math.  Probably should move this out of the query and into code to determine if the job has been "running" too long.
