### ISSUE TITLE
getNextAvailableJob fails because not expecting array of results

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#162]
Well, I assume that's why.  Getting this error:

```
Caused by: com.redhat.lightblue.client.http.LightblueHttpClientException: Error sending lightblue request: {"query":{"field":"whenAvailableDate","op":">=","rvalue":"20150409T22:39:14.769+0000"},"projection":[{"field":"*","include":true,"recursive":true}],"sort":[{"whenAvailableDate":"$asc"}], "range": [0,0]}
        at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:137)
        at com.redhat.lightblue.client.hystrix.LightblueHystrixClient$DataTypeHystrixCommand.run(LightblueHystrixClient.java:69)
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
        ... 48 more
Caused by: com.redhat.lightblue.client.response.LightblueResponseParseException: Error parsing lightblue response: {"status":"COMPLETE","modifiedCount":0,"matchCount":30351,"processed":[{"creationDate":"20150402T13:54:05.000+0000","expectedExecutionMilliseconds":30000,"startDate":"20150409T22:00:00.000+0000","createdBy":"nmalik","_id":"termsJob_321","lastUpdatedBy":"nmalik","jobExecutions":[],"endDate":"20150409T23:00:00.000+0000","whenAvailableDate":"20150409T23:01:00.000+0000","configurationName":"terms","objectType":"migrationJob","lastUpdateDate":"20150402T13:54:05.000+0000","jobExecutions#":0}]}

        at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:107)
        at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:135)
        ... 50 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.redhat.lightblue.migrator.consistency.MigrationJob out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:569)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1121)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:123)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
        at com.redhat.lightblue.client.response.LightblueResponse.parseProcessed(LightblueResponse.java:105)
        ... 51 more
```

**Comment by jewzaam** [comment]
@derek63 @dcrissman something we might need to fix for the release going on now, else migrator will thrash, restarting when it gets this exception in an infinite loop.  I think the quick fix is to make getNextAvailableJob process the response as an array of jobs.

**Comment by dcrissman** [comment]
This feels more like a lightblue-client bug to me. The response looks valid, but my initial guess is maybe it doesn't like "jobExecutions":[]? I would need to write a unit test to check it out.

**Comment by jewzaam** [comment]
To close the thread on it being a client issue, yes it could be something the client handles but the "processed" element is an array of documents.  The issue is we're asking the object mapper to convert an array of docs to a single instance of a java object, which won't work.  I'll add more notes on the client issue.
