### ISSUE TITLE
Sometimes unable to find lightblue configuration properties.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#178]
This exception is thrown every once in a while, but migrations otherwise seem to work.

```
2015-05-04 11:34:11,017 [pool-6-thread-1] ERROR [com.redhat.lightblue.migrator.consistency.MigrationJob] Couldn't update failed job's status
com.redhat.lightblue.client.LightblueClientConfigurationException: Could not find properties resource at lightblue-client.properties
	at com.redhat.lightblue.client.PropertiesLightblueClientConfiguration.fromResource(PropertiesLightblueClientConfiguration.java:100)
	at com.redhat.lightblue.client.PropertiesLightblueClientConfiguration.fromResource(PropertiesLightblueClientConfiguration.java:81)
	at com.redhat.lightblue.client.PropertiesLightblueClientConfiguration.fromDefault(PropertiesLightblueClientConfiguration.java:62)
	at com.redhat.lightblue.client.http.LightblueHttpClient.<init>(LightblueHttpClient.java:42)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.configureClients(MigrationJob.java:437)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.callLightblue(MigrationJob.java:759)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.markExecutionStatusAndEndDate(MigrationJob.java:487)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.run(MigrationJob.java:372)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dcrissman** [comment]
Possibly fixed in https://github.com/lightblue-platform/lightblue-migrator/pull/180

**Comment by dcrissman** [comment]
Issue continues to be random and intermittent.

**Comment by luan-cestari** [comment]
That probably happened due we (or another libary) set a different classloader for the current thread: 
https://github.com/lightblue-platform/lightblue-client/blob/V1.2.0/core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java#L100
https://github.com/lightblue-platform/lightblue-client/blob/V1.2.0/core/src/main/java/com/redhat/lightblue/client/PropertiesLightblueClientConfiguration.java#L81

**Comment by dcrissman** [comment]
What is interesting is that the Migrator does not even have a 'lightblue-client.properties' file (by default), rather it uses primary-lightblue-client.properties. Which means that in MigrationJob.configureClients it is hitting code that it shouldn't be.

https://github.com/lightblue-platform/lightblue-puppet/blob/master/manifests/application/migrator.pp#L235

**Comment by bserdar** [comment]
Is there a static string variable somewhere with that configuration file
name, with a singleton referring to it as a default value?

If so, then the singleton is not a singleton. A different classloader is
loading another instance of it.

**Comment by dcrissman** [comment]
Sorry, clarification to my last update. If you do not pass in a path to the properties file, lightblue-client.properties is the default. For our purposes, the Migrator uses primary-lightblue-client.properties as both the source and destination client configurations as configured by puppet.

**Comment by bserdar** [comment]
No longer an issue
