### ISSUE TITLE
Exception in thread "ConsistencyCheckerRunner" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#78]
These exceptions come in various flavours, but once they start all sorts of other exceptions start coming in and the migrator effectively stops working.

```
Exception in thread "ConsistencyCheckerRunner" java.lang.OutOfMemoryError: Java heap space
	at org.apache.http.util.CharArrayBuffer.expand(CharArrayBuffer.java:61)
	at org.apache.http.util.CharArrayBuffer.append(CharArrayBuffer.java:91)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:245)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:288)
	at com.redhat.lightblue.client.http.LightblueHttpClient.callService(LightblueHttpClient.java:174)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:132)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:140)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getMigrationJobs(ConsistencyChecker.java:183)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:131)
	at java.lang.Thread.run(Thread.java:745)
```
```
Exception in thread "pool-48-thread-1" java.lang.OutOfMemoryError: Java heap space
	at com.fasterxml.jackson.databind.node.ObjectNode.<init>(ObjectNode.java:27)
	at com.fasterxml.jackson.databind.node.JsonNodeFactory.objectNode(JsonNodeFactory.java:309)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:59)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:144)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.findDestinationData(MigrationJob.java:501)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.doDestinationDocumentFetch(MigrationJob.java:402)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.getDestinationDocuments(MigrationJob.java:374)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.run(MigrationJob.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "ConsistencyCheckerRunner" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:2694)
	at java.lang.String.<init>(String.java:203)
	at java.lang.StringBuilder.toString(StringBuilder.java:405)
	at com.redhat.lightblue.client.http.LightblueHttpClient.callService(LightblueHttpClient.java:175)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:132)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:140)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getMigrationJobs(ConsistencyChecker.java:183)
	at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:131)
	at java.lang.Thread.run(Thread.java:745)
```

```

**Comment by dcrissman** [comment]
Possibly related to https://github.com/lightblue-platform/lightblue-rest/issues/106

**Comment by dcrissman** [comment]
This exception came after increasing jvm memory:
-Xmx128m
-Xms128m

**Comment by luan-cestari** [comment]
Try to make to get the heap and analyse the root cause with MAT (the heap can be dump after this error with a jvm parameter and Eclipse MAt have a set of reports that can easily analyse and point out the problem), I would guess there is a memory leak somewhere

**Comment by jewzaam** [comment]
Could be the batch of records being migrated at one time is too big.

**Comment by jewzaam** [comment]
Discussed briefly with @dcrissman and it is likely the set of data being retrieved from the source is too big.  Each job right now for historical data migration spans a 24 hour period.  Some of those are over 10,000 records.  Way migrator works, all of them are loaded into memory at one time.  There are two options:
1) change job time span to something smaller (1 hr)
2) update migrator to support batching up fetching from the source

Option 1 is easy since support is already in place.
Option 2 is some work but not too bad assuming fetching from the source data is via lightblue, since it supports paging.  But that isn't a feature we can use until our next migration probably so option 2 becomes a "do it later" kind of thing.

@dcrissman do we have an issue for supporting option 2 tracked somewhere?

**Comment by luan-cestari** [comment]
@jewzaam @dcrissman I dont know much details of implementation  but it could be nice if there was an strategy flush feature that could trigger the batch not just on the specific time but also if it reach a certain amount of information.

**Comment by jewzaam** [comment]
@luan-cestari short response: yes, let's do that!

This would be two levels of batching.  First is at the size of the job, as determined by the time range that specific job will pull out of the source datastore.  Second is the batching of information loaded from source and reconsiled with destination.

**Comment by luan-cestari** [comment]
I would also think it would be very nice to have that jvm flag I mentioned just to we have do further analysis (the flags that I were thinking   -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath= and -XX:ErrorFile= ). Maybe these flags would be nice to have in all our java projects, what do you think guys?

**Comment by dcrissman** [comment]
I have made the changes for option 1 as @jewzaam outlined above. The migrator needs seem stable at this point. I will let them run overnight and see how things do.

**Comment by dcrissman** [comment]
Still getting OOM exceptions, submitting #81 as a potential solution.

**Comment by dcrissman** [comment]
@luan-cestari my only concern with always including the heap dump would that of disk space. I would hate to compound an already bad state. Maybe if we do decide to always turn that on, we also decide on a retention policy we could enforce somehow?

**Comment by luan-cestari** [comment]
Yeah, we would need some more disk for that (I would say that we would just
store a single heap dump then we would move that to another place). I think
it would be a nice thing to have at least in the firs few months in
production. What do you think @jewzaam   ?

**Comment by jewzaam** [comment]
@dcrissman @luan-cestari disk is out of scope of this issue.  Heap retention could be managed by puppet.

**Comment by jewzaam** [comment]
@dcrissman is this an issue still?

**Comment by dcrissman** [comment]
I am no longer seeing this exception. I will close out.
